branch-defaults:
  default:
    environment: GoogleFacesApp
    group_suffix: null
global:
  application_name: ImageRatingApp
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: null
